import {test,expect} from '@playwright/test'
import type {Page} from '@playwright/test'

async function open(page:Page){
  await page.addInitScript(()=>localStorage.setItem('racememoir-board-v1',JSON.stringify({title:'Interaction',items:[
    {id:'a',kind:'note',title:'A',variant:'paper',x:200,y:150,w:140,h:130,rotation:0},
    {id:'b',kind:'note',title:'B',variant:'paper',x:500,y:300,w:140,h:130,rotation:0}
  ],threads:[]})))
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
}

test('menu arrows do not move canvas objects; Escape returns focus and Enter executes once',async({page},info)=>{
  await open(page)
  const item=page.locator('[data-board-item=a]')
  await item.click()
  const before=await item.getAttribute('style'),trigger=page.getByRole('button',{name:'调整物件层级'})
  await trigger.focus();await page.keyboard.press('ArrowDown')
  const menu=page.getByRole('menu',{name:'调整物件层级'})
  await expect(menu).toBeVisible()
  await expect(page.getByRole('menuitem',{name:'上移一层'})).toBeFocused()
  await page.keyboard.press('End');await expect(page.getByRole('menuitem',{name:'放到指定物件下方'})).toBeFocused()
  await page.keyboard.press('Home');await expect(page.getByRole('menuitem',{name:'上移一层'})).toBeFocused()
  expect(await item.getAttribute('style')).toBe(before)
  await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);await expect(trigger).toBeFocused()
  await expect(item).toHaveAttribute('aria-pressed','true')
  await trigger.press('ArrowDown');await expect(page.getByRole('menuitem',{name:'上移一层'})).toBeFocused();await page.keyboard.press('Home');await page.keyboard.press('Enter')
  await expect(page.locator('.scene>.memory').last()).toHaveAttribute('data-board-item','a')
  expect(await item.getAttribute('style')).toBe(before)
  await trigger.click();await expect(menu).toHaveCSS('opacity','1');await page.screenshot({path:info.outputPath('keyboard-menu.png')})
  await page.getByRole('button',{name:'撤销',exact:true}).click()
  await expect(page.locator('.scene>.memory').first()).toHaveAttribute('data-board-item','a')
})

test('tooltips share styling, stay on screen and Escape only dismisses the hint',async({page})=>{
  await open(page)
  await page.getByRole('button',{name:'添加照片',exact:true}).hover()
  const hint=page.getByRole('tooltip')
  await expect(hint).toContainText('添加照片')
  const color=await hint.evaluate(el=>getComputedStyle(el).backgroundColor)
  await page.locator('[data-board-item=a]').click()
  await page.getByRole('button',{name:'向左旋转'}).hover()
  await expect(hint).toContainText('向左旋转')
  await expect(hint).toHaveCSS('background-color',color)
  const r=(await hint.boundingBox())!;expect(r.x).toBeGreaterThanOrEqual(0);expect(r.y).toBeGreaterThanOrEqual(0)
  await page.keyboard.press('Escape');await expect(hint).toHaveCount(0)
  await expect(page.locator('[data-board-item=a]')).toHaveAttribute('aria-pressed','true')
})

test('adjacent toolbar hints reuse one popup, travel between anchors and dismiss on activation',async({page},info)=>{
  await open(page)
  const hint=page.getByRole('tooltip'),current=hint.locator('[data-current]')
  await page.getByRole('button',{name:'选择',exact:true}).hover()
  await expect(current).toContainText('选择')
  await expect(current.locator('kbd')).toHaveText('V')
  await expect(hint).toHaveCSS('opacity','1')
  const firstPopup=await hint.elementHandle(),first=(await hint.boundingBox())!
  await page.getByRole('button',{name:'添加照片',exact:true}).hover()
  await expect(current).toHaveText('添加照片')
  expect(await hint.evaluate((el,previous)=>el===previous,firstPopup)).toBe(true)
  await expect(hint).toHaveCount(1)
  await expect.poll(async()=>(await hint.boundingBox())!.y).toBeGreaterThan(first.y+25)
  await expect(hint.locator('[data-previous]')).toHaveCount(0)
  await page.screenshot({path:info.outputPath('palette-hint.png')})
  await page.getByRole('button',{name:'添加照片',exact:true}).click()
  await expect(hint).toHaveCount(0)
  await page.getByRole('button',{name:'关闭详情',exact:true}).click()
  await page.locator('[data-board-item=a]').click()
  await page.getByRole('button',{name:'向左旋转'}).hover()
  await expect(current).toHaveText('向左旋转')
  const bottomPopup=await hint.elementHandle()
  await page.getByRole('button',{name:'向右旋转'}).hover()
  await expect(current).toHaveText('向右旋转')
  expect(await hint.evaluate((el,previous)=>el===previous,bottomPopup)).toBe(true)
  await expect(hint.locator('[data-previous]')).toHaveCount(0)
  await page.screenshot({path:info.outputPath('selection-hint.png')})
  await page.getByRole('button',{name:'调整物件层级'}).click()
  await expect(hint).toHaveCount(0)
  await expect(page.getByRole('menu',{name:'调整物件层级'})).toBeVisible()
})

test('reduced motion keeps hints still and disabled history never opens one',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await open(page)
  await page.getByRole('button',{name:'撤销',exact:true}).hover()
  await expect(page.getByRole('button',{name:'撤销',exact:true})).toBeDisabled()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  const trigger=page.getByRole('button',{name:'添加照片',exact:true})
  await trigger.focus()
  const hint=page.getByRole('tooltip')
  await expect(hint).toContainText('添加照片')
  await expect(hint).toHaveCSS('transition-duration','0s')
  await expect(hint).toHaveCSS('filter','none')
  await expect(trigger.locator('svg')).toHaveCSS('transform','none')
  await page.keyboard.press('Tab')
  await expect(hint.locator('[data-current]')).toHaveText('添加奖牌')
  await expect(hint.locator('[data-previous]')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(hint).toHaveCount(0)
})

test('dialog traps focus, restores its trigger and clear confirmation starts on cancel',async({page},info)=>{
  await open(page)
  const share=page.getByRole('button',{name:'分享',exact:true})
  await share.click()
  const dialog=page.getByRole('dialog',{name:'带走这份山野记忆'})
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button',{name:'关闭',exact:true})).toBeFocused()
  for(let i=0;i<8;i++){
    await page.keyboard.press('Tab')
    await expect.poll(()=>dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true)
  }
  await page.screenshot({path:info.outputPath('share-dialog.png')})
  await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(share).toBeFocused()
  await share.click();await page.locator('.ui-dialog-viewport').click({position:{x:5,y:5}})
  await expect(dialog).toHaveCount(0)
  await page.locator('.board-viewport').click({button:'right',position:{x:10,y:180}})
  await page.getByRole('menuitem',{name:'清空画布',exact:true}).click()
  const clear=page.getByRole('dialog',{name:'清空当前画布？'})
  await expect(clear.getByRole('button',{name:'取消',exact:true})).toBeFocused()
  await page.keyboard.press('Escape');await expect(page.locator('[data-board-item]')).toHaveCount(2)
})
