import {test,expect} from '@playwright/test'

test('map draft is cancelled without saving and committed once with undo support',async({page})=>{
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
  const maps=page.locator('.memory-race-map'),initial=await maps.count()
  await page.getByRole('button',{name:'添加地图',exact:true}).click()
  await expect(page.getByRole('heading',{name:'添加赛事地图'})).toBeVisible()
  await expect(maps).toHaveCount(initial)
  await page.getByRole('button',{name:'关闭地图编辑'}).click()
  await page.reload();await page.locator('.records-loading').waitFor({state:'hidden'})
  await expect(maps).toHaveCount(initial)
  await page.getByRole('button',{name:'添加地图',exact:true}).click()
  await page.getByRole('button',{name:'保存并放上画布',exact:true}).click()
  await expect(maps).toHaveCount(initial+1)
  await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(maps).toHaveCount(initial)
  await page.getByRole('button',{name:'重做',exact:true}).click();await expect(maps).toHaveCount(initial+1)
  await page.reload();await page.locator('.records-loading').waitFor({state:'hidden'});await expect(maps).toHaveCount(initial+1)
})

for(const mobile of [false,true])test(`photo calendar selects and clears dates ${mobile?'mobile':'desktop'}`,async({page},info)=>{
  if(mobile)await page.setViewportSize({width:390,height:844})
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
  await page.getByRole('button',{name:'添加照片',exact:true}).click()
  const trigger=page.getByRole('button',{name:'拍摄日期',exact:true})
  await trigger.click()
  const popup=page.getByRole('dialog',{name:'选择拍摄日期'})
  await expect(popup).toBeVisible()
  await popup.getByRole('combobox',{name:'年份',exact:true}).click()
  await page.getByRole('option',{name:'2024',exact:true}).click()
  await popup.getByRole('combobox',{name:'月份',exact:true}).click()
  await page.getByRole('option',{name:'二月',exact:true}).click()
  await popup.getByRole('button',{name:'2024年2月29日',exact:true}).click()
  await expect(trigger).toHaveText('2024-02-29')
  await trigger.click();await expect(popup).toBeVisible()
  await popup.getByRole('combobox',{name:'年份',exact:true}).click()
  await expect(page.getByRole('option',{name:'2024',exact:true})).toHaveAttribute('aria-selected','true')
  await page.screenshot({path:info.outputPath('calendar-year.png')})
  await page.keyboard.press('Escape');await expect(popup).toBeVisible()
  await popup.screenshot({path:info.outputPath('calendar.png')})
  const rect=(await popup.boundingBox())!;expect(rect.x).toBeGreaterThanOrEqual(0);expect(rect.x+rect.width).toBeLessThanOrEqual(mobile?390:1440)
  await page.keyboard.press('Escape');await expect(popup).toHaveCount(0);await expect(trigger).toBeFocused()
  await trigger.click();await popup.getByRole('button',{name:'清除日期'}).click();await expect(trigger).toHaveText('选择日期')
})
