import {test,expect} from '@playwright/test'
test('layer toolbar replaces edit, updates stacking, supports undo and persists',async({page})=>{
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
  const nodes=page.locator('.scene > .memory'),first=nodes.first(),label=(await first.getAttribute('aria-label'))!
  const initial=await nodes.evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')))
  await first.click({position:{x:30,y:80}})
  await expect(page.locator('.record-panel')).toBeVisible()
  await expect(page.getByRole('button',{name:'对齐与分布',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'使用说明',exact:true})).toHaveCount(0)
  await expect(page.locator('.record-panel .editor-explanation,.record-panel .record-heading small,.record-panel p.record-muted:not([role])')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'编辑藏品',exact:true})).toHaveCount(0)
  const menu=page.getByRole('button',{name:'调整物件层级',exact:true})
  await menu.click();await expect(page.getByRole('menuitem',{name:'下移一层',exact:true})).toBeDisabled()
  await page.getByRole('menuitem',{name:'置于顶层',exact:true}).click()
  await expect(nodes.last()).toHaveAttribute('aria-label',label)
  expect(await nodes.last().evaluate(el=>getComputedStyle(el).zIndex)).toBe('auto')
  await menu.click();await expect(page.getByRole('menuitem',{name:'上移一层',exact:true})).toBeDisabled()
  await page.keyboard.press('Escape');await expect(menu).toHaveAttribute('aria-expanded','false')
  await page.getByRole('button',{name:'撤销',exact:true}).click()
  expect(await nodes.evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')))).toEqual(initial)
  await page.getByRole('button',{name:'重做',exact:true}).click();await expect(nodes.last()).toHaveAttribute('aria-label',label)
  await page.reload();await page.locator('.records-loading').waitFor({state:'hidden'});await expect(nodes.last()).toHaveAttribute('aria-label',label)
})

test('medal eyelets and varied photo mounts remain attached after reload and export',async({page},info)=>{
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
  const ring=page.locator('.medal-thread-eyelet').first();await expect(ring).toBeVisible()
  const photo=page.locator('.memory-photo').first(),label=(await photo.getAttribute('aria-label'))!.replace('照片：','')
  const pin=page.getByRole('button',{name:`连接图钉：${label}`,exact:true})
  const before=await pin.getAttribute('style')
  const endpoint=await ring.evaluate(el=>({x:parseFloat((el as HTMLElement).style.left),y:parseFloat((el as HTMLElement).style.top)}))
  const lines=await page.locator('.threads .red-thread').evaluateAll(els=>els.map(el=>el.getAttribute('d')!))
  expect(lines.some(d=>{const a=d.match(/-?\d+(?:\.\d+)?/g)!.map(Number);return Math.hypot(a[0]-endpoint.x,a[1]-endpoint.y)<1||Math.hypot(a[4]-endpoint.x,a[5]-endpoint.y)<1})).toBe(true)
  await page.reload();await page.locator('.records-loading').waitFor({state:'hidden'});await expect(pin).toHaveAttribute('style',before!)
  await page.getByRole('button',{name:'分享',exact:true}).click()
  const download=page.waitForEvent('download');await page.getByRole('button',{name:/导出高清图片/}).click();await (await download).saveAs(info.outputPath('mounts.png'))
})
