import {test,expect} from '@playwright/test'
import type {Page} from '@playwright/test'

async function setup(page:Page,count=2){
  await page.addInitScript(({count})=>{
    if(sessionStorage.getItem('exhibit-fixture'))return
    localStorage.setItem('racememoir-board-v1',JSON.stringify({title:'奖牌展览',items:[
      ...Array.from({length:count},(_,index)=>({id:`m${index}`,kind:'medal',title:`赛事 ${index+1}`,variant:index%2?'silver':'bronze',x:200+(index%4)*240,y:200+Math.floor(index/4)*310,w:180,h:270,rotation:0})),
      {id:'note',kind:'note',title:'终点记忆',x:1300,y:220,w:160,h:160,rotation:0,variant:'paper'},
    ],threads:[{id:'t1',from:'m0',to:'note'},{id:'t2',from:'m1',to:'note'},{id:'t3',from:'m0',to:'m1'}]}))
    sessionStorage.setItem('exhibit-fixture','1')
  },{count})
  await page.goto('/');await page.locator('.records-loading').waitFor({state:'hidden'})
}
async function selectMedals(page:Page){
  const boxes=await page.locator('.scene>.memory-medal').evaluateAll(els=>els.map(el=>{const b=el.getBoundingClientRect();return {x:b.x,y:b.y,right:b.right,bottom:b.bottom}}))
  await page.keyboard.down('Control')
  await page.mouse.move(Math.min(...boxes.map(b=>b.x))-10,Math.min(...boxes.map(b=>b.y))-10)
  await page.mouse.down();await page.mouse.move(Math.max(...boxes.map(b=>b.right))+10,Math.max(...boxes.map(b=>b.bottom))+10,{steps:10});await page.mouse.up();await page.keyboard.up('Control')
  await expect(page.locator('.scene>.memory.selected')).toHaveCount(boxes.length)
}
const saved=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('racememoir-board-v1')||'{}'))

test('medals merge, edit, move, rotate, recover and split without losing their red lines',async({page},info)=>{
  await setup(page);await selectMedals(page)
  const button=(name:string)=>page.getByRole('button',{name,exact:true})
  await button('合并展览框').click();await button('1 × 2 展览框').click()
  const exhibit=page.locator('.scene>.memory-exhibit')
  await expect(exhibit).toHaveCount(1)
  await expect(page.locator('.scene .medal-exhibit-cell:not(.is-empty)')).toHaveCount(2)
  await expect(page.locator('.scene .threads [role=button]')).toHaveCount(3)
  await expect(page.locator('.scene .medal-thread-eyelet')).toHaveCount(2)
  await button('1 × 4 展览框').click();await expect(page.locator('.scene .medal-exhibit-cell')).toHaveCount(4)
  await button('2 × 4 展览框').click();await expect(page.locator('.scene .medal-exhibit-cell')).toHaveCount(8)
  await button('黑框').click()
  await button('后移奖牌 1').click()
  await expect.poll(async()=>(await saved(page)).items.find((i:any)=>i.exhibit)?.exhibit.medals[0].id).toBe('m1')
  await button('编辑奖牌 1').click()
  await expect(button('返回收藏库')).toHaveCount(0)
  await expect(button('放大展示框')).toHaveCount(0)
  const size=page.getByRole('slider',{name:'框内奖牌大小',exact:true})
  await size.fill('140')
  await expect(exhibit.locator('.medal-exhibit-cell').first().locator('.medal-art')).toHaveAttribute('style',/scale\(1.4\)/)
  await expect(exhibit.locator('.medal-exhibit-cell').nth(1).locator('.medal-art')).toHaveAttribute('style',/scale\(1\)/)
  await button('返回展览框').click()
  await expect(page.getByRole('complementary',{name:'奖牌展览框编辑'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'我的收藏库'})).toHaveCount(0)
  await button('编辑奖牌 1').click()
  await expect(size).toHaveValue('140')
  await button('恢复默认大小').click();await expect(size).toHaveValue('100')
  await size.fill('135')
  await page.getByLabel('奖牌名称',{exact:true}).fill('雨中完赛')
  await button('保存修改').click()
  await expect(exhibit.locator('svg[aria-label="雨中完赛"]')).toHaveCount(1)
  await exhibit.press('Enter')
  await page.screenshot({path:info.outputPath('exhibit-editor.png')})
  await button('保存修改').click()
  await expect(page.getByRole('complementary',{name:'奖牌展览框编辑'})).toHaveCount(0)
  await button('适应画布').click()
  const lineBefore=await page.locator('.thread-hit').first().getAttribute('d')
  const box=(await exhibit.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+60,box.y+box.height/2+35,{steps:10});await page.mouse.up()
  await expect(page.locator('.thread-hit').first()).not.toHaveAttribute('d',lineBefore!)
  await button('向右旋转').click()
  await expect(exhibit).toHaveCSS('transform',/matrix/)
  await expect.poll(async()=>(await saved(page)).items.find((i:any)=>i.exhibit)?.rotation).toBe(5)
  await page.reload();await page.locator('.records-loading').waitFor({state:'hidden'})
  await expect(exhibit).toHaveCount(1);await expect(page.locator('.thread-hit')).toHaveCount(3)
  await expect(exhibit.locator('.medal-exhibit-cell').first().locator('.medal-art')).toHaveAttribute('style',/scale\(1.35\)/)
  // Reconnect two individual members through their eyelets while they share one frame.
  await page.locator('.scene .threads [role=button]').last().press('Enter')
  await button('删除选中项').click();await expect(page.locator('.thread-hit')).toHaveCount(2)
  await button('添加连线').click()
  await button('奖牌连接环：赛事 1').press('Enter');await button('奖牌连接环：雨中完赛').press('Enter')
  await button('结束连线').click();await expect(page.locator('.thread-hit')).toHaveCount(3)
  await expect.poll(async()=>(await saved(page)).threads.some((t:any)=>t.from==='m0'&&t.to==='m1')).toBe(true)
  await button('分享').click()
  const png=page.waitForEvent('download');await page.getByRole('button',{name:/导出高清图片/}).click()
  const image=await png;await image.saveAs(info.outputPath('exhibit.png'));expect(await image.failure()).toBeNull()
  const zip=page.waitForEvent('download');await page.getByRole('button',{name:/导出收藏板文件/}).click()
  const path=info.outputPath('exhibit.zip');await(await zip).saveAs(path)
  const picker=page.waitForEvent('filechooser');await page.getByRole('button',{name:/导入收藏板文件/}).click();await(await picker).setFiles(path)
  await expect(page.locator('dialog.modal')).not.toBeVisible()
  await expect(exhibit.locator('.medal-exhibit-cell').first().locator('.medal-art')).toHaveAttribute('style',/scale\(1.35\)/)
  await expect(page.locator('.thread-hit')).toHaveCount(3)
  await exhibit.press('Enter');await page.locator('.selection-bar').getByRole('button',{name:'拆分展览框',exact:true}).click()
  await expect(exhibit).toHaveCount(0);await expect(page.locator('.scene>.memory-medal')).toHaveCount(2);await expect(page.locator('.thread-hit')).toHaveCount(3)
  await button('撤销').click();await expect(exhibit).toHaveCount(1)
  await button('重做').click();await expect(exhibit).toHaveCount(0)
  await button('撤销').click();await exhibit.press('Enter');await page.locator('.selection-bar').getByRole('button',{name:'删除选中项',exact:true}).click()
  await expect(page.locator('.thread-hit')).toHaveCount(0)
  await button('撤销').click();await expect(exhibit).toHaveCount(1);await expect(page.locator('.thread-hit')).toHaveCount(3)
})

test('eight medals fill 2x4 and disable smaller layouts, with an internally scrolling editor',async({page},info)=>{
  await setup(page,8);await selectMedals(page)
  const button=(name:string)=>page.getByRole('button',{name,exact:true})
  await button('合并展览框').click()
  await expect(button('1 × 2 展览框')).toBeDisabled();await expect(button('1 × 4 展览框')).toBeDisabled()
  await button('2 × 4 展览框').click()
  await expect(page.locator('.scene .medal-exhibit-cell:not(.is-empty)')).toHaveCount(8)
  await expect(button('1 × 4 展览框')).toBeDisabled()
  await page.screenshot({path:info.outputPath('eight-medals.png')})
  await page.setViewportSize({width:390,height:640})
  expect(await page.locator('.record-scroll').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1)
  await button('保存修改').click()
  await page.locator('.scene>.memory-exhibit').press('Enter')
  await page.getByRole('complementary',{name:'奖牌展览框编辑'}).getByRole('button',{name:'拆分展览框',exact:true}).click()
  await expect(page.locator('.scene>.memory-medal')).toHaveCount(8)
})
