import {useEffect,useRef} from 'react'
import {ChevronDown,CloudCheck,Download,Library,Share2,Upload} from 'lucide-react'
import type {Board} from '../domain/model'
import MountainLogo from '../shared/MountainLogo'
interface Props {board:Board;menu:boolean;setMenu:(open:boolean)=>void;saved:string;saveError:string;saveFailed:boolean;onRetry:()=>void;onRename:(title:string)=>void;onImport:()=>void;onExport:()=>void;onLibrary:()=>void;onShare:()=>void;onHelp:()=>void}
export default function Topbar({board,menu,setMenu,saved,saveError,saveFailed,onRetry,onRename,onImport,onExport,onLibrary,onShare,onHelp}:Props){
  const menuRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(!menu)return;const close=(e:PointerEvent)=>{if(!menuRef.current?.contains(e.target as Node))setMenu(false)};window.addEventListener('pointerdown',close);return()=>window.removeEventListener('pointerdown',close)},[menu,setMenu])
  return <header className="topbar"><div className="brand"><MountainLogo/><span>山径线索板</span></div><span className="header-divider"/><div className="board-menu" ref={menuRef}><button className="board-title" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{board.title}<ChevronDown size={17}/></button>{menu && <div className="dropdown"><label>收藏板名称<input aria-label="收藏板名称" maxLength={28} defaultValue={board.title} onBlur={e=>{if(e.target.value.trim() && e.target.value.trim()!==board.title)onRename(e.target.value.trim())}} onKeyDown={e=>{if(e.key==='Enter'){e.currentTarget.blur();setMenu(false)}}}/></label><button onClick={()=>{onImport();setMenu(false)}}><Upload size={16}/>导入收藏板</button><button onClick={()=>{onExport();setMenu(false)}}><Download size={16}/>导出收藏板文件</button><div className="dropdown-foot">{board.items.length} 件藏品 · {board.threads.length} 段连接</div></div>}</div>
      <div className="header-actions"><button className="share-button library-button" aria-label="打开收藏库" onClick={onLibrary}><Library size={18}/><span>收藏库</span></button><span className={`save-status ${saveError?'error':''}`} role="status" aria-live="polite" title={saveError||'画布和已提交的收藏文件保存在此浏览器；侧栏内容需点击保存'}><CloudCheck size={18}/><span>{saved}</span>{saveFailed&&<button onClick={onRetry}>重试</button>}</span><button className="share-button" onClick={onShare}><Share2 size={17}/><span>分享</span></button><span className="header-divider"/><button className="avatar" onClick={onHelp} aria-label="使用指南"><img src="/images/hiking.jpg" alt="山野旅人"/></button></div>
    </header>
}
