// Refresh locally hosted Google Fonts; run only when intentionally updating fonts.
import {mkdir,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'

const families=[['Inter','inter','400..850'],['Caveat','caveat','400..600'],['Noto Sans JP','notosansjp','400..850'],['Klee One','kleeone','400']]
const headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'}
async function download(url){const r=await fetch(url,{headers});if(!r.ok)throw new Error(`${r.status}: ${url}`);return Buffer.from(await r.arrayBuffer())}
const dir=new URL('../public/fonts/international/',import.meta.url)
await mkdir(dir,{recursive:true})
let css='/* Locally hosted, unicode-range subsets. Generated by scripts/vendor-fonts.mjs. */\n'
const sources=[]
for(const [name,id,weights] of families){
 const url=`https://fonts.googleapis.com/css2?family=${name.replaceAll(' ','+')}:wght@${weights}&display=swap`
 let text=(await download(url)).toString()
 const urls=[...new Set([...text.matchAll(/url\((https:[^)]+)\)/g)].map(m=>m[1]))]
 for(let i=0;i<urls.length;i+=8)await Promise.all(urls.slice(i,i+8).map(async source=>{
  const bytes=await download(source),hash=createHash('sha256').update(bytes).digest('hex').slice(0,12)
  const file=`${id}-${hash}.woff2`
  if(bytes.subarray(0,4).toString()!=='wOF2')throw new Error(`Expected WOFF2: ${source}`)
  await writeFile(new URL(file,dir),bytes)
  text=text.replaceAll(source,`/fonts/international/${file}`)
 }))
 await writeFile(new URL(`${id}-OFL.txt`,dir),await download(`https://raw.githubusercontent.com/google/fonts/main/ofl/${id}/OFL.txt`))
 css+=`\n/* ${name} */\n${text}`
 sources.push(`- ${name}: ${url} — ${urls.length} WOFF2 subsets, SIL OFL 1.1 (see ${id}-OFL.txt).`)
 console.log(`${name}: ${urls.length} subsets`)
}
await writeFile(new URL('../src/i18n/fonts.css',import.meta.url),css)
await writeFile(new URL('README.md',dir),`# Local interface and handwriting fonts\n\nDownloaded ${new Date().toISOString().slice(0,10)} from Google Fonts. No runtime requests to Google.\n\n${sources.join('\n')}\n\nRun \`node scripts/vendor-fonts.mjs\` to refresh intentionally. Files retain upstream glyphs and unicode ranges; filenames include a content hash. Japanese subsets are requested only when their glyphs are needed.\n`)
